import { AudioType, DocumentType, ImageType, TextType, VideoType } from '../enums'

export function getExtByMimeType(mimeType: ImageType | DocumentType | VideoType | AudioType | TextType) {
  return {
    [ImageType.JPEG]: 'jpg',
    [ImageType.PNG]: 'png',
    [ImageType.GIF]: 'gif',
    [ImageType.WEBP]: 'webp',
    [ImageType.BMP]: 'bmp',
    [ImageType.TIFF]: 'bmp',
    [ImageType.ICO]: 'ico',
    [ImageType.SVG]: 'svg',
    [ImageType.AVIF]: 'avif',
    [ImageType.HEIC]: 'heic',
    [DocumentType.DOC]: 'doc',
    [DocumentType.PDF]: 'pdf',
    [DocumentType.DOCX]: 'docx',
    [DocumentType.XLS]: 'xls',
    [DocumentType.XLSX]: 'xlsx',
    [DocumentType.PPT]: 'ppt',
    [DocumentType.PPTX]: 'pptx',
    [VideoType.AVI]: 'avi',
    [VideoType.MP4]: 'mp4',
    [VideoType.FLV]: 'flv',
    [VideoType.MOV]: 'mov',
    [VideoType.WEBM]: 'mkv',
    [VideoType.MKV]: 'mkv',
    [AudioType.MP3]: 'mp3',
    [AudioType.WAV]: 'wav',
    [AudioType.AAC]: 'aac',
    [AudioType.OGG]: 'ogg',
    [AudioType.FLAC]: 'flac',
    [TextType.TEXT]: 'txt',
    [TextType.CSV]: 'csv',
  }[mimeType]
}
