export enum EventTopic {
  UserCreated = 'user.created',
  ChannelsPublishTaskPlatformScheduled = 'channels.publish.task.platform_scheduled',
  ChannelsPublishTaskWaitingForUserAction = 'channels.publish.task.waiting_for_user_action',
  ChannelsPublishTaskPublished = 'channels.publish.task.published',
  ChannelsPublishTaskFailed = 'channels.publish.task.failed',
  ChannelsPublishTaskCanceled = 'channels.publish.task.canceled',
  ChannelsPublishTaskUpdateStarted = 'channels.publish.task.update_started',
  ChannelsPublishTaskUpdated = 'channels.publish.task.updated',
  ChannelsPublishTaskUpdateFailed = 'channels.publish.task.update_failed',
  ChannelsAccountConnected = 'channels.account.connected',
  ChannelsAccountUpdated = 'channels.account.updated',
  ChannelsAccountOffline = 'channels.account.offline',
  ChannelsCredentialRefreshed = 'channels.credential.refreshed',
  ChannelsCredentialExpired = 'channels.credential.expired',
  ChannelsCredentialRevoked = 'channels.credential.revoked',
  ChannelsCredentialRefreshFailed = 'channels.credential.refresh_failed',
  ChannelsAuthFailed = 'channels.auth.failed',
  ChannelsPublishFlowCreated = 'channels.publish.flow.created',
  ChannelsPublishTaskCreated = 'channels.publish.task.created',
  ChannelsPublishTaskEnqueued = 'channels.publish.task.enqueued',
  ChannelsPublishTaskStarted = 'channels.publish.task.started',
  ChannelsPublishTaskFinalizeTimeout = 'channels.publish.task.finalize_timeout',
  ChannelsAnalyticsAccountFetched = 'channels.analytics.account.fetched',
  ChannelsAnalyticsWorkFetched = 'channels.analytics.work.fetched',
  ChannelsAnalyticsFetchFailed = 'channels.analytics.fetch_failed',
  ChannelsEngagementCommentCreated = 'channels.engagement.comment_created',
}
